# version: '3' # Versión de docker-compose

services:
  db: # Nombre cualquiera del servicio
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      # - postgres-db:/var/lib/postgresql/data # Ejemplo de name volume
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com

# volumes:
#   postgres-db:
#     external: true

# Las últimas tres líneas configuran el volumen postgres-db como un volumen externo. 
# Esto significa que Docker no creará ni administrará el volumen, 
# sino que espera que el volumen ya exista en el host.